### ISSUE TITLE
User preferences not loading

### ISSUE THREAD

**Issue by marcogrueter** [anomalylabs/preferences-module#5]
I've noticed, that the user preferences are not loaded. After selecting a language for the admin in the preferences module, the language doesn't change.

I'm pretty sure that this is because the "SetLocale" listener is fired before the user is logged in.
The "field" function in the preferences module is getting using the user id from the auth object (Illuminate\Auth\Guard), to lookup the prefernces, but the user object is still null at this point.

So the preferences module probably has to listen to an auth.login event or the UserLoggedIn Event of the users module or something.

If you can give me any hints on how to solve this, I'd like to give it a go.

**Comment by RyanThompson** [comment]
it doesn't effect the user - it should be setting the app.locale config value

**Comment by RyanThompson** [comment]
Here's the listener: https://github.com/anomalylabs/preferences-module/blob/1.0/master/src/Listener/ConfigureStreams.php

**Comment by RyanThompson** [comment]
And the listen def: https://github.com/anomalylabs/preferences-module/blob/1.0/master/src/PreferencesModuleServiceProvider.php#L31

**Comment by marcogrueter** [comment]
When the SetLocale command is dispatched, the handler function gets the locale value from the preferences:

https://github.com/anomalylabs/preferences-module/blob/1.0/master/src/Listener/Command/SetLocale.php
Line 31

    if ($request->segment(1) === 'admin' && $locale = $preferences->get('streams::admin_locale'))

https://github.com/anomalylabs/preferences-module/blob/1.0/master/src/Preference/PreferenceRepository.php
Line 105, function field

    $preference = $this->model->where('user_id', $this->auth->id())->where('key', $key)->first();

$this->auth->id() returns null at this point, which means that the default value gets returned, which is null. The if in line 31 of the SetLocale command evaluates to false and the locale doesn't get set and remains on the value in the config file.

**Comment by RyanThompson** [comment]
Ahhhhhh

So this needs to listen to https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Http/Middleware/ApplicationReady.php

**Comment by marcogrueter** [comment]
Yeah, that would probably work.

**Comment by marcogrueter** [comment]
One thing I'm thinking about: maybe the preferences module should be integrated into the users module. Wouldn't be such a stretch, since they're coupled anyway.

I can't really think of a major advantage of moving it, but the preferences kind of belong there :)

**Comment by RyanThompson** [comment]
I think preferences / settings need tighter integration in general.. See slack for some discussion

**Comment by RyanThompson** [comment]
This has been fixed since ^_^
